import type { GemDef, ItemDef } from "@/lib/game/types";

export const ITEMS: Record<string, ItemDef> = {
  "cloth-pants": {
    id: "cloth-pants",
    name: "Cloth Pants",
    slot: "legs",
    questStat: "dexterity",
    affinity: "warden",
    rarity: "common",
    basePower: 1,
    sellValue: 4,
    description: "Rough orchard weave. Better than nothing.",
  },
  "farm-gloves": {
    id: "farm-gloves",
    name: "Farm Gloves",
    slot: "hands",
    questStat: "dexterity",
    affinity: "herald",
    rarity: "common",
    basePower: 1,
    sellValue: 4,
    description: "Stained with apple sap and honest work.",
  },
  "walking-staff": {
    id: "walking-staff",
    name: "Walking Staff",
    slot: "weapon",
    questStat: "strength",
    affinity: "sage",
    rarity: "common",
    basePower: 1,
    sellValue: 5,
    description: "A sturdy branch carved into a traveler's friend.",
  },
  "leather-cap": {
    id: "leather-cap",
    name: "Leather Cap",
    slot: "head",
    questStat: "strength",
    affinity: "warden",
    rarity: "common",
    basePower: 1,
    sellValue: 5,
    description: "Keeps the sun off and the thoughts in.",
  },
  "market-boots": {
    id: "market-boots",
    name: "Market Boots",
    slot: "feet",
    questStat: "dexterity",
    affinity: "herald",
    rarity: "uncommon",
    basePower: 2,
    sellValue: 10,
    description: "Soft soles for weaving through crowded stalls.",
  },
  "bronze-chest": {
    id: "bronze-chest",
    name: "Barbarian's Bronze Vest",
    slot: "chest",
    questStat: "strength",
    affinity: "warden",
    rarity: "uncommon",
    basePower: 2,
    sellValue: 14,
    description: "Hammered plates that still smell faintly of forge smoke.",
  },
  "scholar-ring": {
    id: "scholar-ring",
    name: "Scholar's Copper Ring",
    slot: "ring",
    questStat: "intelligence",
    affinity: "sage",
    rarity: "uncommon",
    basePower: 2,
    sellValue: 12,
    description: "Etched with tide charts no longer accurate.",
  },
  "warlock-ring": {
    id: "warlock-ring",
    name: "Warlock's Iron Ring",
    slot: "ring",
    questStat: "intelligence",
    affinity: "herald",
    rarity: "rare",
    basePower: 3,
    sellValue: 22,
    description: "Cold to the touch, warmer when you speak.",
  },
  "canyon-amulet": {
    id: "canyon-amulet",
    name: "Canyon Wind Amulet",
    slot: "amulet",
    questStat: "intelligence",
    affinity: "sage",
    rarity: "rare",
    basePower: 3,
    sellValue: 24,
    description: "A hollow stone that whispers when held to the ear.",
  },
  "ash-helm": {
    id: "ash-helm",
    name: "Ashplate Helm",
    slot: "head",
    questStat: "strength",
    affinity: "warden",
    rarity: "rare",
    basePower: 3,
    sellValue: 26,
    description: "Basalt cheek guards that shrug off heat shimmer.",
  },
  "ring-of-success": {
    id: "ring-of-success",
    name: "Ring of Returning Rain",
    slot: "ring",
    questStat: "intelligence",
    affinity: "herald",
    rarity: "legendary",
    basePower: 5,
    sellValue: 80,
    description:
      "A legendary band said to remember the last storm that blessed Orwen.",
  },
  "shore-sandals": {
    id: "shore-sandals",
    name: "Tidewalker Sandals",
    slot: "feet",
    questStat: "dexterity",
    affinity: "sage",
    rarity: "uncommon",
    basePower: 2,
    sellValue: 11,
    description: "Wet rope soles that refuse to slip on slick timber.",
  },
  "mill-hammer": {
    id: "mill-hammer",
    name: "Millwright Hammer",
    slot: "weapon",
    questStat: "strength",
    affinity: "herald",
    rarity: "uncommon",
    basePower: 2,
    sellValue: 13,
    description: "Heavy enough to turn a stuck gear—or a stubborn door.",
  },
  "herald-gloves": {
    id: "herald-gloves",
    name: "Herald's Soft Gloves",
    slot: "hands",
    questStat: "dexterity",
    affinity: "herald",
    rarity: "rare",
    basePower: 3,
    sellValue: 20,
    description: "For shaking hands and picking locks with equal grace.",
  },
  "field-bandage": {
    id: "field-bandage",
    name: "Field Bandage",
    rarity: "common",
    basePower: 0,
    sellValue: 6,
    healAmount: 8,
    description: "Clean cloth and orchard salve. Restores a little health.",
  },
  "dried-apple": {
    id: "dried-apple",
    name: "Dried Apple",
    rarity: "common",
    basePower: 0,
    sellValue: 4,
    healAmount: 5,
    description: "Sweet and chewy. Not a feast, but it steadies you.",
  },
  "shore-tonic": {
    id: "shore-tonic",
    name: "Shore Tonic",
    rarity: "uncommon",
    basePower: 0,
    sellValue: 14,
    healAmount: 14,
    description: "Brine, herbs, and something that fizzes. Clears the fog from your bones.",
  },
  "ash-draught": {
    id: "ash-draught",
    name: "Ash Draught",
    rarity: "rare",
    basePower: 0,
    sellValue: 28,
    healAmount: 22,
    description: "Bitter tablelands medicine. Heals deep cuts and the wounded stagger.",
  },
  "trail-ration": {
    id: "trail-ration",
    name: "Trail Ration",
    rarity: "common",
    basePower: 0,
    sellValue: 3,
    healAmount: 10,
    description: "Reed-wrapped fish and herbs. Cheap road food that still steadies you.",
  },
  "iron-greaves": {
    id: "iron-greaves",
    name: "Iron Greaves",
    slot: "legs",
    questStat: "dexterity",
    affinity: "warden",
    rarity: "uncommon",
    basePower: 3,
    sellValue: 18,
    description: "Riveted plates for long marches through scorched grass.",
  },
  "herald-blade": {
    id: "herald-blade",
    name: "Herald's Ash Blade",
    slot: "weapon",
    questStat: "strength",
    affinity: "herald",
    rarity: "rare",
    basePower: 4,
    sellValue: 32,
    description: "Iron and ash alloy folded thin — loud in a fight, persuasive in a room.",
  },
  "reinforced-vest": {
    id: "reinforced-vest",
    name: "Reinforced Ash Vest",
    slot: "chest",
    questStat: "strength",
    affinity: "warden",
    rarity: "rare",
    basePower: 4,
    sellValue: 34,
    description: "Layered ash alloy over iron plate. Forge smoke never quite leaves it.",
  },
  "apple-wood": {
    id: "apple-wood",
    name: "Apple Wood",
    rarity: "common",
    basePower: 0,
    sellValue: 2,
    material: true,
    description: "Dry orchard branches. Fuel, hafts, and smoke racks.",
  },
  "pale-reed": {
    id: "pale-reed",
    name: "Pale Reed",
    rarity: "common",
    basePower: 0,
    sellValue: 2,
    material: true,
    description: "Wind-scraped grassland reed. Weavers and cooks both want bundles.",
  },
  "herb-bundle": {
    id: "herb-bundle",
    name: "Herb Bundle",
    rarity: "common",
    basePower: 0,
    sellValue: 3,
    material: true,
    description: "Wilted tops and wild mint. Stew and tonic start here.",
  },
  "raw-fish": {
    id: "raw-fish",
    name: "Raw Fish",
    rarity: "common",
    basePower: 0,
    sellValue: 3,
    material: true,
    description: "Still slick with brine or creek water. Cook before eating.",
  },
  "silver-scale": {
    id: "silver-scale",
    name: "Silver Scale",
    rarity: "uncommon",
    basePower: 0,
    sellValue: 8,
    material: true,
    description: "A rare minnow scale that catches light like forgotten rain.",
  },
  "copper-ore": {
    id: "copper-ore",
    name: "Copper Ore",
    rarity: "common",
    basePower: 0,
    sellValue: 4,
    material: true,
    description: "Green-streaked stone from canyon veins.",
  },
  "iron-ore": {
    id: "iron-ore",
    name: "Iron Ore",
    rarity: "common",
    basePower: 0,
    sellValue: 5,
    material: true,
    description: "Heavy scrap and workable lumps from ledger quarries.",
  },
  "coal": {
    id: "coal",
    name: "Coal",
    rarity: "common",
    basePower: 0,
    sellValue: 4,
    material: true,
    description: "Basalt seam coal. Forges and mills burn it hot.",
  },
  "ash-ore": {
    id: "ash-ore",
    name: "Ash Ore",
    rarity: "uncommon",
    basePower: 0,
    sellValue: 9,
    material: true,
    description: "Warm mineral from the tablelands. Smiths prize the streaks.",
  },
  "gem-chip": {
    id: "gem-chip",
    name: "Gem Chip",
    rarity: "uncommon",
    basePower: 0,
    sellValue: 10,
    material: true,
    description: "A rough chip that might hide mist, ember, or song inside.",
  },
  "copper-bar": {
    id: "copper-bar",
    name: "Copper Bar",
    rarity: "common",
    basePower: 0,
    sellValue: 10,
    material: true,
    description: "Smelted orange metal. Ready for the anvil.",
  },
  "iron-bar": {
    id: "iron-bar",
    name: "Iron Bar",
    rarity: "uncommon",
    basePower: 0,
    sellValue: 16,
    material: true,
    description: "Quenched iron bar. Heavy and honest.",
  },
  "iron-plate": {
    id: "iron-plate",
    name: "Iron Plate",
    rarity: "uncommon",
    basePower: 0,
    sellValue: 12,
    material: true,
    description: "Hammered plate stock ready for greaves or vest layers.",
  },
  "ash-alloy": {
    id: "ash-alloy",
    name: "Ash Alloy",
    rarity: "rare",
    basePower: 0,
    sellValue: 18,
    material: true,
    description: "Iron fused with tablelands ash. Smiths use it for serious work.",
  },
  "cooked-fish": {
    id: "cooked-fish",
    name: "Cooked Fish",
    rarity: "common",
    basePower: 0,
    sellValue: 6,
    material: true,
    description: "Smoked fillet. Safe to eat on the road.",
  },
};

export const GEMS: Record<string, GemDef> = {
  "raw-ember": {
    id: "raw-ember",
    name: "Raw Emberstone",
    affinity: "warden",
    tier: 1,
    bonus: 2,
    description: "Warm mineral that steadies the body.",
  },
  "raw-mist": {
    id: "raw-mist",
    name: "Raw Mistpearl",
    affinity: "sage",
    tier: 1,
    bonus: 2,
    description: "Clouded pearl that sharpens insight.",
  },
  "raw-song": {
    id: "raw-song",
    name: "Raw Songglass",
    affinity: "herald",
    tier: 1,
    bonus: 2,
    description: "Thin glass that hums when you speak nearby.",
  },
};

export const LORE_SYMBOLS = ["☾", "△", "☁", "✦", "☰", "◎"] as const;
export const LORE_SOLUTION = ["☁", "☾", "✦"] as const;
