import type { QuestDef } from "@/lib/game/types";

export const QUESTS: QuestDef[] = [
  // Orchard
  {
    id: "orchard-haul",
    locationId: "merrick-orchard",
    name: "Haul Water Casks",
    description:
      "Merrick needs barrels dragged from the creek bed. Your back will complain; the trees will not.",
    level: 1,
    stat: "strength",
    durationSeconds: 90,
    goldReward: 4,
    itemPool: ["walking-staff", "leather-cap", "dried-apple"],
    itemChance: 0.28,
    gemChance: 0.05,
  },
  {
    id: "orchard-prune",
    locationId: "merrick-orchard",
    name: "Prune Brittle Limbs",
    description:
      "Dead branches threaten to crack onto the path. Climb carefully and cut clean.",
    level: 1,
    stat: "dexterity",
    durationSeconds: 80,
    goldReward: 3,
    itemPool: ["cloth-pants", "farm-gloves", "field-bandage"],
    itemChance: 0.3,
    gemChance: 0.05,
    storyFlagOnSuccess: "orchard_help",
  },
  {
    id: "orchard-listen",
    locationId: "merrick-orchard",
    name: "Listen to Merrick's Ledger",
    description:
      "The old farmer keeps rainfall notes in a cracked book. Patterns hide between the ink blots.",
    level: 1,
    stat: "intelligence",
    durationSeconds: 100,
    goldReward: 4,
    itemPool: ["scholar-ring"],
    itemChance: 0.32,
    gemChance: 0.08,
    storyFlagOnSuccess: "mill_unlocked",
    unlockLocationId: "stone-mill",
  },
  // Square
  {
    id: "square-bargain",
    locationId: "tarowen-square",
    name: "Bargain with Dry Traders",
    description:
      "Convince merchants to share water credits for orchard labor. Charm goes further than coin.",
    level: 2,
    stat: "intelligence",
    durationSeconds: 120,
    goldReward: 6,
    rumor: true,
    itemPool: ["market-boots", "scholar-ring"],
    itemChance: 0.34,
    gemChance: 0.1,
    storyFlagOnSuccess: "shore_unlocked",
    unlockLocationId: "northern-shore",
  },
  {
    id: "square-lift",
    locationId: "tarowen-square",
    name: "Clear the Well Debris",
    description:
      "Someone dumped masonry into the town well. Lift stones until the bucket can drop again.",
    level: 2,
    stat: "strength",
    durationSeconds: 110,
    goldReward: 6,
    itemPool: ["bronze-chest", "leather-cap"],
    itemChance: 0.3,
    gemChance: 0.08,
  },
  {
    id: "square-courier",
    locationId: "tarowen-square",
    name: "Courier the Seed Satchel",
    description:
      "Race a satchel of drought-resistant seeds to the grassland shepherds before dusk.",
    level: 2,
    stat: "dexterity",
    durationSeconds: 100,
    goldReward: 5,
    itemPool: ["farm-gloves", "market-boots", "field-bandage"],
    itemChance: 0.32,
    gemChance: 0.08,
  },
  // Grass
  {
    id: "grass-sheep",
    locationId: "ashen-grass",
    name: "Search for Lost Sheep",
    description:
      "It is not uncommon for shepherds to lose sheep while tending herds. Track them and earn gratitude—and trousers.",
    level: 1,
    stat: "dexterity",
    durationSeconds: 70,
    goldReward: 3,
    itemPool: ["cloth-pants", "farm-gloves"],
    itemChance: 0.3,
    gemChance: 0.06,
  },
  {
    id: "grass-fence",
    locationId: "ashen-grass",
    name: "Mend Windblown Fences",
    description:
      "Posts lean like tired soldiers. Hammer them true before night thieves arrive.",
    level: 2,
    stat: "strength",
    durationSeconds: 100,
    goldReward: 5,
    itemPool: ["walking-staff", "bronze-chest"],
    itemChance: 0.3,
    gemChance: 0.08,
  },
  {
    id: "grass-herbs",
    locationId: "ashen-grass",
    name: "Catalog Drought Herbs",
    description:
      "A healer wants notes on which plants still green. Observation beats haste.",
    level: 2,
    stat: "intelligence",
    durationSeconds: 110,
    goldReward: 5,
    itemPool: ["scholar-ring"],
    itemChance: 0.35,
    gemChance: 0.1,
  },
  // Mill
  {
    id: "mill-turn",
    locationId: "stone-mill",
    name: "Turn the Stuck Wheel",
    description:
      "With no river, the mill wheel must be forced by muscle. Brace, push, and pray for rain.",
    level: 3,
    stat: "strength",
    durationSeconds: 140,
    goldReward: 8,
    itemPool: ["mill-hammer", "bronze-chest"],
    itemChance: 0.32,
    gemChance: 0.12,
    storyFlagOnSuccess: "canyon_unlocked",
    unlockLocationId: "clara-canyon",
  },
  {
    id: "mill-gears",
    locationId: "stone-mill",
    name: "Oil the Hidden Gears",
    description:
      "Narrow crawlspaces hide seized gears. Dexterity keeps knuckles intact.",
    level: 3,
    stat: "dexterity",
    durationSeconds: 130,
    goldReward: 8,
    itemPool: ["herald-gloves", "market-boots"],
    itemChance: 0.34,
    gemChance: 0.12,
  },
  {
    id: "mill-math",
    locationId: "stone-mill",
    name: "Recalculate Flow Charts",
    description:
      "Old diagrams assume a river. Redesign the channels for bucket brigades.",
    level: 3,
    stat: "intelligence",
    durationSeconds: 150,
    goldReward: 9,
    itemPool: ["warlock-ring", "scholar-ring"],
    itemChance: 0.36,
    gemChance: 0.14,
  },
  // Shore
  {
    id: "shore-comb",
    locationId: "northern-shore",
    name: "Comb the Beach",
    description:
      "To the untrained eye the beach is debris. You are convinced relics remain for those who know the shapes.",
    level: 3,
    stat: "intelligence",
    durationSeconds: 150,
    goldReward: 8,
    itemPool: ["shore-sandals", "warlock-ring", "shore-tonic"],
    itemChance: 0.4,
    gemChance: 0.15,
  },
  {
    id: "shore-trade",
    locationId: "northern-shore",
    name: "Trade with Vagrants",
    description:
      "Beachcombers gather loot but misjudge value. Patient trading turns scrap into profit.",
    level: 4,
    stat: "intelligence",
    durationSeconds: 180,
    goldReward: 11,
    rumor: true,
    itemPool: ["warlock-ring", "canyon-amulet"],
    itemChance: 0.38,
    gemChance: 0.16,
    storyFlagOnSuccess: "tables_unlocked",
    unlockLocationId: "blackened-tables",
  },
  {
    id: "shore-haul",
    locationId: "northern-shore",
    name: "Drag Wreck Timber",
    description:
      "Salvage beams for Tarowen's well repair. Salt-slick wood fights every step.",
    level: 3,
    stat: "strength",
    durationSeconds: 140,
    goldReward: 8,
    itemPool: ["mill-hammer", "ash-helm", "ash-draught"],
    itemChance: 0.32,
    gemChance: 0.12,
  },
  {
    id: "shore-rumor",
    locationId: "northern-shore",
    name: "Listen for Shore Rumors",
    description:
      "Around driftwood fires, someone mentions a sealed shrine and three symbols that still hold rain.",
    level: 4,
    stat: "intelligence",
    durationSeconds: 160,
    goldReward: 10,
    rumor: true,
    itemPool: ["canyon-amulet"],
    itemChance: 0.36,
    gemChance: 0.18,
    storyFlagOnSuccess: "shrine_unlocked",
    unlockLocationId: "sealed-shrine",
  },
  // Canyon
  {
    id: "canyon-ledge",
    locationId: "clara-canyon",
    name: "Traverse Wind Ledges",
    description:
      "Cross a knife-edge path while the canyon howls. One misstep and the story ends early.",
    level: 4,
    stat: "dexterity",
    durationSeconds: 170,
    goldReward: 12,
    itemPool: ["herald-gloves", "shore-sandals"],
    itemChance: 0.35,
    gemChance: 0.16,
  },
  {
    id: "canyon-map",
    locationId: "clara-canyon",
    name: "Map the Crack Network",
    description:
      "Scholars pay for accurate sketches of fissures that drink every drop of moisture.",
    level: 4,
    stat: "intelligence",
    durationSeconds: 180,
    goldReward: 12,
    itemPool: ["canyon-amulet", "warlock-ring"],
    itemChance: 0.4,
    gemChance: 0.18,
  },
  {
    id: "canyon-boulder",
    locationId: "clara-canyon",
    name: "Shift the Fallen Gate",
    description:
      "A rockfall blocks the old smuggler road. Brace and lever until light returns.",
    level: 4,
    stat: "strength",
    durationSeconds: 170,
    goldReward: 11,
    itemPool: ["ash-helm", "mill-hammer"],
    itemChance: 0.34,
    gemChance: 0.15,
  },
  // Tablelands
  {
    id: "tables-ash",
    locationId: "blackened-tables",
    name: "Clear Ash from Watchtowers",
    description:
      "Climb blackened stairs and shovel drifts of volcanic ash until the horizon reappears.",
    level: 5,
    stat: "strength",
    durationSeconds: 200,
    goldReward: 14,
    itemPool: ["ash-helm", "bronze-chest", "ash-draught"],
    itemChance: 0.36,
    gemChance: 0.2,
  },
  {
    id: "tables-survey",
    locationId: "blackened-tables",
    name: "Survey Heat Vents",
    description:
      "Record which vents still breathe. Patterns may explain why clouds refuse Orwen.",
    level: 5,
    stat: "intelligence",
    durationSeconds: 210,
    goldReward: 15,
    itemPool: ["canyon-amulet", "warlock-ring"],
    itemChance: 0.42,
    gemChance: 0.22,
  },
  {
    id: "tables-dash",
    locationId: "blackened-tables",
    name: "Dash Between Shade Stones",
    description:
      "Sprint from basalt shade to shade before the plateau cooks your resolve.",
    level: 5,
    stat: "dexterity",
    durationSeconds: 190,
    goldReward: 14,
    itemPool: ["herald-gloves", "shore-sandals"],
    itemChance: 0.38,
    gemChance: 0.2,
  },
  // Shrine
  {
    id: "shrine-study",
    locationId: "sealed-shrine",
    name: "Study the Sealed Door",
    description:
      "Three symbols wait. Compare them to shoreline carvings and orchard ledgers.",
    level: 5,
    stat: "intelligence",
    durationSeconds: 200,
    goldReward: 16,
    itemPool: ["canyon-amulet"],
    itemChance: 0.4,
    gemChance: 0.25,
    storyFlagOnSuccess: "shrine_studied",
  },
  {
    id: "shrine-brace",
    locationId: "sealed-shrine",
    name: "Brace the Cracked Arch",
    description:
      "Hold the arch steady while dust rains down. Strength keeps history from collapsing.",
    level: 5,
    stat: "strength",
    durationSeconds: 190,
    goldReward: 15,
    itemPool: ["ash-helm"],
    itemChance: 0.36,
    gemChance: 0.22,
  },
  {
    id: "shrine-open",
    locationId: "sealed-shrine",
    name: "Open the Rainward Gate",
    description:
      "With lore solved and courage gathered, push the door. If fortune smiles, Orwen remembers rain.",
    level: 6,
    stat: "intelligence",
    durationSeconds: 220,
    goldReward: 20,
    itemPool: ["ring-of-success"],
    itemChance: 0.45,
    gemChance: 0.3,
    storyFlagOnSuccess: "chapter_complete",
  },
];

export const QUEST_MAP = Object.fromEntries(
  QUESTS.map((q) => [q.id, q]),
) as Record<string, QuestDef>;
